### ISSUE TITLE
Question: Is there any plans of doing remote redux debugging

### ISSUE THREAD

**Issue by LordLyng** [brianegan/flutter_redux_dev_tools#2]
There is a lot of tools out there like https://github.com/zalmoxisus/remote-redux-devtools og even VS Code extensions that can handle the redux state. And give a good debugging experience.

Is there any plans to make it so that you can enter a remote address and port instead of embedding the tools in the app? Maybe via redux middleware or a custom enhancer.

**Comment by brianegan** [comment]
Hey there -- I'd definitely thought of doing this! The Redux Dev Tools haven't quite been as popular as other libs I've published, so I've spent a bit less time on doing something like that, but it should definitely be possible.

**Comment by hyjfine** [comment]
It would be a very useful tool when flutter is popular @brianegan

**Comment by wardpenney** [comment]
@LordLyng @hyjfine It exists now at https://github.com/MichaelMarner/dart-redux-remote-devtools

It worked fine, but I am removing it now in favor of this repo. With the remote tools, you need to hard-code the IP address of your remote in the flutter code (no way to get it from terminal and pass it via flutter CLI). So, that becomes quite painful, unless you can guarantee your remote dev tools IP won't change.

**Comment by MichaelMarner** [comment]
hey @wardpenney 

Author of dart-redux-remote-devtools here. The way we deal with this in our code is to have an `environment` class that is excluded from Git, but setup for each developer based on their workstation. That way, while you still need to "hard code" an IP address, it isn't as much of a pain for multi-developer teams.

There are other options for using environment variables to generate code before `flutter run` which would also solve your problem. For example:

https://medium.com/flutter-community/use-environment-variables-in-ci-cd-for-flutter-apps-cbd6d9ac82c

**Comment by brianegan** [comment]
Thanks! Since this one is fixed by @MichaelMarner I'll close it out for now.
